### ISSUE TITLE
Control polling time

### ISSUE THREAD

**Issue by GwonsooLee** [DevopsArtFactory/goployer#5]
**Is your feature request related to a problem? Please describe.**
Controlling `polling time` when doing healthcheck.

**Describe the solution you'd like**
There are two ways to implement this.
1. send `polling-duration` argument from command line
2. specify `polling_duration` configuration in manifest file

**Additional context**
Polling time means the duration of seconds for doing healthchecking process for newly created autoscaling groups and previous version of autoscaling group. Default polling time is 60 seconds.
https://github.com/DevopsArtFactory/goployer/blob/master/pkg/tool/common.go#L14

**Comment by asbubam** [comment]
Can I take this issue?

**Comment by jupitersong** [comment]
:+1:

**Comment by GwonsooLee** [comment]
> Can I take this issue?

Sure! I was thinking that we could use argument like `--polling-time`(this is just an example, please use any name if suitable).
Later, if needed, we could add polling time configuration in each manifest file in order to apply different polling time according to the application. 

For now, simple change seems reasonable.
Thanks @asbubam
