### ISSUE TITLE
Docker image with pre-built goployer

### ISSUE THREAD

**Issue by GwonsooLee** [DevopsArtFactory/goployer#9]
Provide official docker image which contains latest-released goployer.

This could be helpful when using goployer with codebuild or jenkins.

Opinion needed :) @jupitersong

**Comment by GwonsooLee** [comment]
@asbubam Please share your opinion~ :)

**Comment by asbubam** [comment]
> @asbubam Please share your opinion~ :)

Yes, sure. It's absolutely necessary.

**Comment by GwonsooLee** [comment]
Latest version of goployer installed in docker container.
You could  use docker image for goployer like this.

`docker run devopsart/goployer:latest goployer`
